- packages/aws-lambda-graphql/README.md
- packages/aws-lambda-graphql/src/createDynamoDBEventProcessor.ts
- packages/aws-lambda-graphql/src/createHttpHandler.ts
- packages/aws-lambda-graphql/src/createMemoryEventProcessor.ts
- packages/aws-lambda-graphql/src/createWsHandler.ts
- packages/aws-lambda-graphql/src/execute.ts
- packages/aws-lambda-graphql/src/types/graphql.ts
> Allow custom context

- packages/aws-lambda-graphql/package.json
- packages/aws-lambda-graphql/src/client/operationProcessor.ts
- yarn.lock
> Replace ulid with uuid v1 and make it possible to use own id generator

- packages/aws-lambda-graphql/package.json
- packages/aws-lambda-graphql/src/client/operationProcessor.ts
- packages/aws-lambda-ws-link/package.json
- packages/aws-lambda-ws-link/src/WebSocketLink.ts
- yarn.lock
> Use incremental operation id generator

- packages/aws-lambda-graphql/src/DynamoDBSubscriptionManager.ts
- packages/aws-lambda-graphql/src/MemorySubscriptionManager.ts
- packages/aws-lambda-graphql/src/__mocks__/aws-sdk.ts
- packages/aws-lambda-graphql/src/__tests__/DynamoDBSubscriptionManager.test.ts
- packages/aws-lambda-graphql/src/__tests__/createWsHandler.test.ts
- packages/aws-lambda-graphql/src/client/__tests__/operationProcessor.test.ts
- packages/aws-lambda-graphql/src/client/__tests__/services.test.ts
- packages/aws-lambda-graphql/src/client/operationProcessor.ts
- packages/aws-lambda-graphql/src/client/services.ts
- packages/aws-lambda-graphql/src/createDynamoDBEventProcessor.ts
- packages/aws-lambda-graphql/src/createMemoryEventProcessor.ts
- packages/aws-lambda-graphql/src/createWsHandler.ts
- packages/aws-lambda-graphql/src/fixtures/helpers.ts
- packages/aws-lambda-graphql/src/formatMessage.ts
- packages/aws-lambda-graphql/src/helpers/parseOperationFromEvent.ts
- packages/aws-lambda-graphql/src/protocol/index.ts
- packages/aws-lambda-graphql/src/types/graphql.ts
- packages/aws-lambda-graphql/src/types/subscriptions.ts
- packages/chat-example-server/cloudformation.yml
- packages/chat-example-server/serverless.yml
Closes #7 
TODO:
This PR introduces another table `SubcriptionOperations`.
> Add a way to unsubscribe client from specific subscription

- packages/aws-lambda-graphql/package.json
- packages/aws-lambda-graphql/src/createDynamoDBEventProcessor.ts
- packages/aws-lambda-graphql/src/createHttpHandler.ts
- packages/aws-lambda-graphql/src/createMemoryEventProcessor.ts
- packages/aws-lambda-graphql/src/createWsHandler.ts
- packages/aws-lambda-graphql/src/execute.ts
- packages/aws-lambda-graphql/src/fixtures/schema.ts
- packages/aws-lambda-graphql/src/types/aws.ts
- packages/aws-lambda-graphql/src/types/graphql.ts
- yarn.lock
> Add lambda's context to GraphQL context

- packages/aws-lambda-graphql/src/createHttpHandler.ts
> Normalise headers to lowercase

- packages/aws-lambda-graphql/src/__tests__/createDynamoDBEventProcessor.test.ts
- packages/aws-lambda-graphql/src/createDynamoDBEventProcessor.ts
- packages/aws-lambda-graphql/src/createMemoryEventProcessor.ts
> add support for context to event processors

- packages/aws-lambda-graphql/src/__tests__/createWsHandler.test.ts
- packages/aws-lambda-graphql/src/execute.ts
Pass context stored in connection state to context builder function alongside internal context
> Provide connection context to context builder function

- packages/aws-lambda-graphql/src/PubSub.ts
- packages/aws-lambda-graphql/src/__tests__/PubSub.test.ts
- packages/aws-lambda-graphql/src/__tests__/createDynamoDBEventProcessor.test.ts
- packages/aws-lambda-graphql/src/createDynamoDBEventProcessor.ts
- packages/aws-lambda-graphql/src/createMemoryEventProcessor.ts
- packages/aws-lambda-graphql/src/types/subscriptions.ts
Resolves #45. Trying to save an object which has a value of an empty string is failing for me and I need this functionality.
> Serialize payload of event

- .circleci/config.yml
- packages/aws-lambda-graphql/src/__tests__/PubSub.test.ts
- packages/aws-lambda-graphql/src/__tests__/createWsHandler.test.ts
- packages/aws-lambda-graphql/src/createDynamoDBEventProcessor.ts
- packages/aws-lambda-graphql/src/createMemoryEventProcessor.ts
- packages/aws-lambda-graphql/src/createWsHandler.ts
> Return proper response on websocket disconnect

- packages/aws-lambda-graphql/src/PubSub.ts
- packages/aws-lambda-graphql/src/__tests__/PubSub.test.ts
> Do not allow publishing event with empty name

- CHANGELOG.md
> Add  changelog

- README.md
- commitlint.config.js
- package.json
- packages/aws-lambda-graphql/src/ArrayPubSub.ts
- packages/aws-lambda-graphql/src/PubSub.ts
- packages/aws-lambda-graphql/src/__tests__/DynamoDBEventProcessor.test.ts
- packages/aws-lambda-graphql/src/__tests__/PubSub.test.ts
- yarn.lock
> feat: make JSON serialization optional

- CHANGELOG.md
- README.md
- packages/aws-lambda-graphql/package.json
- packages/aws-lambda-graphql/src/RedisConnectionManager.ts
- packages/aws-lambda-graphql/src/RedisSubscriptionManager.ts
- packages/aws-lambda-graphql/src/__tests__/RedisConnectionManager.test.ts
- packages/aws-lambda-graphql/src/__tests__/RedisSubscriptionManager.test.ts
- packages/aws-lambda-graphql/src/__tests__/Server.test.ts
- packages/aws-lambda-graphql/src/errors/index.ts
- packages/aws-lambda-graphql/src/helpers/index.ts
- packages/aws-lambda-graphql/src/helpers/prefixRedisKey.ts
- packages/aws-lambda-graphql/src/index.ts
- yarn.lock
You can now use Redis as your data storage for connections and subscriptions information.
Example:
```js
import {
RedisConnectionManager,
RedisSubscriptionManager,
} from 'aws-lambda-graphql';
import Redis from 'ioredis';
const redisClient = new Redis({
port: 6379, // Redis port
host: '127.0.0.1', // Redis host
});
const subscriptionManager = new RedisSubscriptionManager({
redisClient,
});
const connectionManager = new RedisConnectionManager({
subscriptionManager,
redisClient,
});
```
> SubscriptionManager and ConnectionManager using Redis

- package.json
- packages/aws-lambda-graphql/src/ArrayPubSub.ts
- packages/aws-lambda-graphql/src/DynamoDBConnectionManager.ts
- packages/aws-lambda-graphql/src/DynamoDBEventProcessor.ts
- packages/aws-lambda-graphql/src/DynamoDBSubscriptionManager.ts
- packages/aws-lambda-graphql/src/MemoryEventProcessor.ts
- packages/aws-lambda-graphql/src/MemorySubscriptionManager.ts
- packages/aws-lambda-graphql/src/RedisConnectionManager.ts
- packages/aws-lambda-graphql/src/Server.ts
- packages/aws-lambda-graphql/src/WebSocketConnectionManager.ts
- packages/aws-lambda-graphql/src/__tests__/ApolloClient.integration.test.ts
- packages/aws-lambda-graphql/src/__tests__/Server.test.ts
- packages/aws-lambda-graphql/src/__tests__/withFilter.test.ts
- packages/aws-lambda-graphql/src/fixtures/helpers.ts
- packages/aws-lambda-graphql/src/fixtures/schema.ts
- packages/aws-lambda-graphql/src/fixtures/server.ts
- packages/aws-lambda-graphql/src/withFilter.ts
- packages/chat-example-app/src/components/Messages.tsx
- yarn.lock
> feat: pass Sec-WebSocket-Protocol headers during connect phase

- packages/aws-lambda-graphql/src/Server.ts
- packages/aws-lambda-graphql/src/__tests__/Server.test.ts
> fix: check sec-websocket-protocol only if provided

- packages/aws-lambda-graphql/src/DynamoDBConnectionManager.ts
- packages/aws-lambda-graphql/src/DynamoDBEventStore.ts
- packages/aws-lambda-graphql/src/DynamoDBSubscriptionManager.ts
- packages/aws-lambda-graphql/src/PubSub.ts
- packages/aws-lambda-graphql/src/RedisConnectionManager.ts
- packages/aws-lambda-graphql/src/RedisSubscriptionManager.ts
- packages/aws-lambda-graphql/src/Server.ts
- packages/aws-lambda-graphql/src/__tests__/Server.test.ts
> feat: validate constructor options

- packages/aws-lambda-graphql/README.md
- packages/aws-lambda-graphql/src/DynamoDBConnectionManager.ts
- packages/aws-lambda-graphql/src/DynamoDBEventProcessor.ts
- packages/aws-lambda-graphql/src/PubSub.ts
Added optional debug flag to `PubSub.ts`, `DynamoDBConnectionManager.ts` and `DynamoDBEventProcessor.ts`
Might be used to add some other logs if needed.
README updated to add new parameters
Closes #102
> feat: add debug mode to console.log events

- packages/aws-lambda-graphql/src/DynamoDBSubscriptionManager.ts
> fix: correctly paginate through subscriptions

- packages/aws-lambda-graphql/src/Server.ts
- packages/aws-lambda-graphql/src/__tests__/Server.test.ts
- packages/aws-lambda-graphql/src/helpers/parseOperationFromEvent.ts
- packages/aws-lambda-graphql/src/protocol/index.ts
> fix: handle connection_terminate in $default route to avoid throw error

- package.json
- packages/aws-lambda-graphql/package.json
- packages/aws-lambda-graphql/src/execute.ts
- packages/chat-example-app/package.json
- packages/chat-example-server/package.json
- yarn.lock
> feat: update graphql

- README.md
- packages/aws-lambda-graphql/src/DynamoDBEventProcessor.ts
Also found one in `DynamoDBEventProcessor`
> Just fixing some typos in README
